export { default as Layout } from "./layout/Layout";
export { default as Hero } from "./hero/Hero";
export { default as Navigation } from "./navigation/Navigation";
export { default as SectionTitle } from "./sectionTitle/SectionTitle";
export { default as WhatWeOffer } from "./whatWeOffer/WhatWeOffer";
export { default as PaymentPlan } from "./paymentPlan/PaymentPlan";
export { default as Portfolio } from "./portfolio/Portfolio";
export { default as WhoWeAre } from "./whoWeAre/WhoWeAre";
export { default as Blog } from "./blog/Blog";
